export const locationNames = [
<<<<<<< HEAD
  "MAIN CAMPUS"
  
=======
  "Aalapot",
  "Ashrang",
  "Baad Bhanjyang",
  "Badikhel",
  "Bageswori",
  "Bajrayogini (Sankhu)",
  "Balambu",
  "Balkot",
  "Baluwa",
  "Bhadrabas",
  "Bhaktapur",
  "Bhardev",
  "Bhattedanda",
  "Bhimdhunga",
  "Bisankhunarayan",
  "Budanilkantha",
  "Bukhel",
  "Bungamati",
  "Chalnakhel",
  "Chandanpur",
  "Changunarayan",
  "Chapagaun",
  "Chapali Bhadrakali",
  "Chhaimale",
  "Chhaling",
  "Chhampi",
  "Chitapol",
  "Choughare",
  "Chunikhel",
  "Daanchhi",
  "Dadhikot",
  "Dahachok",
  "Dalchoki",
  "Daxinkali",
  "Devichour",
  "Dhapakhel",
  "Dhapasi",
  "Dharmasthali",
  "Dhusel",
  "Dukuchhap",
  "Duwakot",
  "Futung",
  "Gagalphedi",
  "Gimdi",
  "Godamchaur",
  "Godawari",
  "Gokarneswor",
  "Goldhunga",
  "Gonggabu",
  "Gothatar",
  "Gotikhel",
  "Gundu",
  "Harisiddhi",
  "Ichang Narayan",
  "Ikudol",
  "Imadol",
  "Indrayani",
  "Jharuwarasi",
  "Jhaukhel",
  "Jhor Mahankal",
  "Jitpurphedi",
  "Jorpati",
  "Kabhresthali",
  "Kaleswor",
  "Kapan",
  "Kathmandu",
  "Kautunje",
  "Khadka Bhadrakali",
  "Khokana",
  "Kirtipur",
  "Lalitpur (Patan)",
  "Lamatar",
  "Lapsiphedi",
  "Lele",
  "Lubhu",
  "Machhegaun",
  "Madhyapur Thimi",
  "Mahadevathan",
  "Mahankal",
  "Malta",
  "Manikhel",
  "Manmaiju",
  "Matatirtha",
  "Mulpani",
  "Nagarkot",
  "Naglebhare",
  "Naikap Naya Bhanjyang",
  "Naikap Purano Bhanjyang",
  "Nallu",
  "Nankhel",
  "Nayapati",
  "Pukhulachhi",
  "Pyutar",
  "Ramkot",
  "Sainbu",
  "Sangla",
  "Sankhu",
  "Satungal",
  "Setidevi",
  "Seuchatar",
  "Sheshnarayan",
  "Siddhipur",
  "Sipadol",
  "Sirutar",
  "Sitapaila",
  "Sudal",
  "Sunakothi",
  "Sundarijal",
  "Suntol",
  "Talkududechour",
  "Tathali",
  "Thaiba",
  "Thankot",
  "Thecho",
  "Thuladurlung",
  "Tikathali",
  "Tinthana",
  "Tokha Chandeswori",
  "Tokha Sarswoti",
>>>>>>> 4786f39bb399142a28edc51e6a1b9c61edc071b0
];
